### ISSUE TITLE
Text Description about the MS-COCO dataset

### ISSUE THREAD

**Issue by secondlevel** [changzheng123/L-CoDe#1]
Hello, 

I would like to ask if the MS-COCO dataset has text description about the images? Or do these descriptions need to be defined by ourselves? 

Even though COCO 2015 dataset have text description. But most of the text descriptions in this dataset have nothing to do with color.

If they don't have the text description about the MS-COCO dataset, and I want to know if it is possible that you can provide the whole dataset with the Google Drive link? 

Thank you so much.

**Comment by changzheng123** [comment]
You can get the full captions of MS-COCO here "https://drive.google.com/file/d/1rSnbIGNDGZeHlsUlLdahj0RJ9oo6lgH9/view?pli=1
". But in the paper, we said, "we keep the images whose captions contain adjectives and have 59K training images and 2.4K validation images left". So we didn't use all the images in the MS-COCO. The images in the JSON files are all we used to train and evaluate the model. The image numbers are the same as MS-COCO.
