### ISSUE TITLE
FileNotFoundError: No such file or directory: 'checkpoint/emb_13.pth'

### ISSUE THREAD

**Issue by ChchNiu** [changzheng123/L-CoDe#4]
Hello!
Thank you for your excellent work.
I am currently attempting to replicate your results, but I have encountered an issue related to a missing pretrained model. Specifically, I am receiving the following error: "FileNotFoundError: No such file or directory: 'checkpoint/emb_13.pth'".
Would it be possible for you to share the 'emb_13.pth' pretrained model file?

**Comment by changzheng123** [comment]
Replied by email
